name = "hammal"
account_id = "6c9300a627976a94aff9600f18036e32"
main = "src/index.ts"
workers_dev = true
compatibility_date = "2024-06-08"

kv_namespaces = [
	 { binding = "HAMMAL_CACHE", id = "you kv id" }
]
